### ISSUE TITLE
Firmware for 8 bit MKS GEN L + TMC2208 + MKS TFT24 + DUAL Z

### ISSUE THREAD

**Issue by primus192** [lachusmadeti/Tarantula-RS#3] opened 2021-09-10 13:43 UTC
Hi. Many users recieved their tarantula RS with MKS GEN L. Can you make newest firmware for this configuration? Thanks.

**Comment by lachusmadeti** [comment] 2021-09-15 13:55
Hi,

I try to make it and compile for test.

Best regards

**Comment by lachusmadeti** [comment] 2021-09-15 13:55
Hi,

I try to make it and compile for test.

Best regards

**Comment by lachusmadeti** [comment] 2021-09-15 14:14
The MKS Gen L is V1 or V2?

**Comment by MBK-sysop** [comment] 2021-10-02 14:54
MKS Gen_L V1.0 with TMC2208 and display MKS TFT24 V1 OTP  - This set is currently sold. They say the problem is the availability of components after the pandemic...

**Comment by lachusmadeti** [comment] 2021-12-22 14:19
I close the issue, the firmware was added and it´s updated.

**Closed as completed by lachusmadeti** 2021-12-22 14:19 UTC
